#!/bin/bash

# Install package from setup.py
python setup.py install

# Install classic notebook extension
jupyter nbextension install --py jupyter_dash --sys-prefix

# Install a JupyterLab extension
jupyter labextension install extensions/jupyterlab
