#!/bin/bash

# Build wheel
python setup.py bdist_wheel

# Show build packages
ls dist/

# Install wheel
python -m pip install dist/jupyter-dash-*.whl

# List installed packages
python -m pip list

# Rebuild JupyterLab to include jupyterlab-dash extension
jupyter lab build
